server:
  port: 8818

# --------------------------------------- 用户自定义修改项 ------------------------------------
# web登录管理员账号密码
web:
  account: admin
  password: admin123456
# --------------------------------------- 用户自定义修改项 ------------------------------------

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:king-detective.db
  sql:
    init:
      mode: always
  ai:
    openai:
      api-key: sk-xxx
      base-url: https://api.siliconflow.cn
      chat:
        options:
#          model: deepseek-ai/DeepSeek-R1-0528-Qwen3-8B
          model: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B

mybatis-plus:
  mapper-locations: classpath*:com/tony/kingdetective/mapper/xml/*.xml

logging:
  pattern:
    # console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %msg%n"
  level:
    com.oracle.bmc: error
    c.o.b.h.c.j: error

# 密钥文件存放目录（如果是docker部署则不用修改）
oci-cfg:
  boot-broadcast-url: https://backend.oci-helper.de5.net/api/boot
  boot-broadcast-channel: https://api.telegram.org/bot8252348609:AAHQsW95nrozzWpXRjKRVa0Ul4oyWrxn_wI/sendMessage?chat_id=@oci_helper
#  key-dir-path: /app/king-detective/keys
  key-dir-path: C:\\Users\\yatao\\Desktop